### ISSUE TITLE
Abstract Renderer used by default instead of DialogRenderer?

### ISSUE THREAD

**Issue by cfv1984** [aurelia/dialog#129]
Hi!  I'm using aurelia-dialog@0.5.10, and configuring it by setting ```config.centerHorizontalOnly = true``` in ```aurelia.use.plugin('aurelia-dialog', function(){/*here*/})```.
 If I dont set anything else in there, the renderer I'm ending up in the DialogSettings is ```Renderer``` instead of, as expected, ```DialogRenderer```. 

Not passing absoluely anything in there sets the proper renderer, but obviously, does not apply any further config.

I've momentarily solved this by calling ```config.useDefaults()``` inside my configuration function, but I was under the impression that defaults are used, ehm, by default? Like, if I don't provide a needed value, a default should be used? 

If this is not a real bug, is there any place in the docs where language could be added explaining this? I'm pretty sure I'm not the only one who's been weirded out by this.

**Comment by EisenbergEffect** [comment]
It is by design, however, I do think it's a bit misleading. @jedd-ahyoung Do you think we could improve this somehow? For example, use a default for whatever option isn't explicitly indicated?

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect I don't see why not. The configuration builder as it is is not as polished as it should be. Ideally, it should have some type of method that exports the configuration once configuration is complete, populating the DI containers with the correct methods, etc.

@cfv1984 Note that, even with the proposed change, you'll need to set your settings on `config.settings

**Comment by jedd-ahyoung** [comment]
@EisenbergEffect I don't see why not. The configuration builder as it is is not as polished as it should be. Ideally, it should have some type of method that exports the configuration once configuration is complete, populating the DI containers with the correct methods, etc. This way, we can easily provide default configuration without the use of `useDefaults()`. I'm not sure how the exports will work, though. Perhaps the `ai-` elements should always be exported?

@cfv1984 Note that, even with the proposed change, you'll need to set your settings on `config.settings` instead of `config` itself.
