### ISSUE TITLE
Issue with opacity, post update to RC.

### ISSUE THREAD

**Issue by Sayan751** [aurelia/dialog#182]
I was using custom css for the opacity of active overlay (as per the documentation) as follows:
```
ai-dialog-overlay.active {
    background-color: black;
    opacity: .5;
}
```

It was working before I updated to aurelia rc and correspondingly to `aurelia-dialog@1.0.0-beta.2.0.0`.  Now, post update, I found two issues. One is already mentioned [here](https://github.com/aurelia/dialog/issues/181), and the other is that the `opacity` in custom css has no effect as can be seen in the screenshot below. I also found that `opacity` is set to 1 by an explicit `<style></style>` . Though I am not sure what was the case before, as I never had this issue, and I never had to check that. 

Am I doing something incorrectly here? Or if there is any workaround for this?

Thank you.

![2016-07-14_10h00_48](https://cloud.githubusercontent.com/assets/3128881/16832350/3203559e-49aa-11e6-87ba-f50b6a31bbe2.png)

**Comment by EisenbergEffect** [comment]
@jedd-ahyoung Ping.

**Comment by jedd-ahyoung** [comment]
@Sayan751 This is happening because the way that the dialog style works has been changed. Style can now be added at dialog configuration time (when you configure the dialog plugin at startup). The reason you're seeing what you're seeing is because the dialog plugin now injects a style element into the body for its own use. This is the correct behavior.

To change this, use the `useCSS` method in the dialogConfiguration, like so:

```
export function configure(aurelia) {
  aurelia.use
    .plugin('aurelia-dialog', config => {
      config.useCSS(''myCSSStringHere');
      ...
    });
```

This will override the default CSS. Note that you'll need to include all of the dialog styles here - partial updates won't work.

**Comment by AdamWillden** [comment]
@jedd-ahyoung that snippet could do with being added to the documentation or the readme.md

**Comment by glen-84** [comment]
Why is it even using `opacity` to start with? Wouldn't `visibility` work? Then we wouldn't have to change the built-in CSS or use an overly-specific selector to change the opacity.

**Comment by shanegray** [comment]
Quick fix for opacity:
```
ai-dialog-overlay.active {
  background-color: black;
  opacity: .5 !important; // override injected 
}
```

**Comment by Inawire** [comment]
Thanks @shanegray that worked for me since that was the only thing I wanted to override. Note on June 4, 2017 I had to override ux-dialog-overlay.active. I think at some point ai- was changed to ui-

To others, there are some other ways to do this with the API but I can only find references to it in these closed issues not on the doc hub. This trick was quick and simple but not for all.
