### ISSUE TITLE
UI issue: rounded corner (border-radius) doesn't work on Safari with latest ai-dialog{display:table}

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/dialog#222]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-beta.3.0.1
- **Operating System:**
  OSX 10.12
- **Node Version:**
  6.7.0
- **NPM Version:**
  3.10.3
- **JSPM OR Webpack AND Version**
  aurelia-cli 0.21.0
- **Browser:**
  Safari 10.0
- **Language:**
  all

**Current behavior:**
On Safari, sharp corners with white background stick out the rounded border.
This issue doesn't appear on Firefox or Chrome. I have not tested on IE/Edge.

**Expected/desired behavior:**
By pass this Safari related css issue if possible.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
@PWKad Can you take a look?

**Comment by PWKad** [comment]
This is due to the border that is applied to the dialog.  For the border to work we would have to refactor the styles again.  Bootstrap for instance uses an additional nested element to combat this.  After looking at it at high res I don't think you can see the border anyway.  I'm voting to remove the border on `ai-dialog` to close this issue.

Can anyone confirm that the border is unnoticable?

**Comment by huochunpeng** [comment]
This is a Safari-only issue. I am fine without rounded corner, but the fix might annoy some other developers who don't care about Safari.

**Comment by PWKad** [comment]
The rounded corner would stay it is the border that is almost in discernable

**Comment by huochunpeng** [comment]
Great. Yes the border is not noticeable because of the dark shadow around it.

**Comment by PWKad** [comment]
Closed by https://github.com/aurelia/dialog/commit/d60e2346f5458998c388c4d9147bc674dabbc103
