### ISSUE TITLE
Dialog open in activate does not work on first load with router.

### ISSUE THREAD

**Issue by glennpierce** [aurelia/dialog#233]
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Linux fedora 23

* **Node Version:**
6.2.2

* **NPM Version:**
3.9.5

* **JSPM OR Webpack AND Version**
webpack 2.1.0-beta.22

* **Browser:**
Chrome 53

* **Language:**
TypeScript 2.0.0

**Current behavior:**

I am calling this.dialogService.open from an activate method.
When I first go to the page or refresh the page so the constructor is called the dialog open does not result in the dialog being displayed.
However, if I click on another entry in the top level menu provided by the router and then naviagate back to the original page the dialog displays fine. In ther later case the constructor is not called.
The only difference I can is is hasActiveDialog is true when the dialog displays but false when it does not work at the point open is called.

**Expected/desired behavior:**

Can't create a gistrun with aurelia-dialog so have made a repository at
https://github.com/glennpierce/test/tree/master/src

Go to any page and do a refresh and the dialog fails to display. Clinking between toplevel menu items will display the doalog.

* **What is the expected behavior?**

The dialog should display of first load.

* **What is the motivation / use case for changing the behavior?**

To display a dialog :)

**Comment by StrahilKazlachev** [comment]
I'll have time to check it as early as tomorrow. If you want you can chain a `.catch` to the `.open` method and see the error, if any.

**Comment by glennpierce** [comment]
Not sure if I'm doing anything wrong but I can't get a catch handler to trigger.

**Comment by StrahilKazlachev** [comment]
@glennpierce It's strange that the catch doesn't work. Also I'm not much into webpack, but in the `webpack.config.js` I don't see anything about the dialog, is it normal? I'll first try it on the sample app first

**Comment by StrahilKazlachev** [comment]
So I tried it with the skeleton-navigation/skeleton-esnext and it worked. When I try to run your sample I get `TypeError: webpack.validateSchema is not a function` after running `npm start`.

**Comment by glennpierce** [comment]
I just used npm install aurelia-dialog --save like in the install instructions.
Don't think I needed to edit webpack.config.js

I have updated the source to solve the validateSchema error.

I had to use a different version of webpack

ie
-    "webpack": "2.1.0-beta.22",
-    "webpack-dev-server": ">=2.1.0-beta.0 || ^2.1.0"
+    "webpack": "^2.1.0-beta.22",
+    "webpack-dev-server": "^1.16.2"

**Comment by StrahilKazlachev** [comment]
Ok, so I manged to run it and got `Unhandled rejection Error: Cannot find module './77.html'.`. Check #231 and #213. I'll look though where the promise chain breaks and the rejection is not propagated to the `.open()` method.

**Comment by glennpierce** [comment]
If it helps stepping through the code slowly the dialog does display when returning the promise from the showDialog function but then something closes it. However, I can't seem to capture what does that.

**Comment by StrahilKazlachev** [comment]
@glennpierce Found it, sorry for the delay. Using this webpack setup threw me off. The problem is that the modal container is put in the `body`, also `aurelia-app="main"` is put on the `body`, so when navigation completes(after `activate` settles), the content of the `body` is replaced. You can try to add a `div` and put `aurelia-app="main"` on it. Then the dialog will be visible after the navigation completes.

**Comment by glennpierce** [comment]
No worries about the delay. Thanks a lot for helping.
I did your suggestion of putting aurelia-app="main" in a div and it works great. It may be worth added a note in the docs as I would think it may be a common mistake.
Again thanks for the help.

**Comment by PWKad** [comment]
@glennpierce @StrahilKazlachev Is this an issue with the dialog that needs a note or with WebPack?

**Comment by StrahilKazlachev** [comment]
@PWKad I would say neither, it's just how Aurelia works. But it doesn't hurt to add note.

**Comment by PWKad** [comment]
Gotcha, sounded specific to WebPack (presumably the plugin is loaded before the app is replaced?) but if it is cross-loaders than I think we can add a quick note.

**Comment by jods4** [comment]
@StrahilKazlachev so I'm moving the discussion about webpack + dialog startup here.

I think that the `<body>` think is a gotcha and not a great experience for users. It also happens that you don't want a `<div>` at the root (happened to me before).

The cause here is that Webpack resolves everything very quickly and synchronously. This can result in a different execution sequence from what you might have been used to with AMD (or others).

I can offer you two suggestions to remedy the situation.

1) @niieani encountered similar issue with tests failing with Webpack at first.
We fixed the Aurelia booting sequence (there were unobserved Promises...) and exposed a Promise to reflect the boot status (there was an event but if you haven't subscribed when it fires then it's useless).

Now you can easily and reliably execute code after Aurelia has started by using the `starting` Promise exported by `aurelia-bootstrapper`. It resolves when _all_ Aurelia application on the page have started.
```js
import { starting } from "aurelia-bootstrapper";
starting.then(() => { 
  // Do stuff you need to do when Aurelia has started
});
```

2) It would be even better if you did not modify the DOM at startup.
I am not sure what you insert in DOM at first, I suspect a backdrop `<div>`? 
In my own dialog library, we insert and remove the backgroup (and the rest) each time a dialog is shown/hidden.
Lazily modifying the DOM has several advantages:
- faster startup
- smaller DOM at runtime
- less interferences with other code

**Comment by StrahilKazlachev** [comment]
@jods4 I think there is some misunderstanding, I'll try to explain what happens.
- the dialog does **no** DOM modifications at startup
- the dialog modifies the DOM only when a dialog is being open, when it is being attached to the DOM tree(for now)
- `starting` is too early
- the issue comes from Aurelia replacing the content of the `aurelia-app` marked element
  - this issue was about opening a dialog in the `.activate` hook of the route VM on first app load
    - the dialog gets open(placed in the `body`) *during* the navigation
    - when the navigation completes the content of the `aurelia-app`(`body`) element gets replaced, but the dialog is already in the `body`, so it gets removed

1. I *still* think this is not Webpack specific.
    - *will address* it in the docs
2. I'm only not sure why the contents of `app.html` are not rendered before/while *navigating*(the route content do go in the `router-view`), hence replacing the `aurelia-app` content early on.
