### ISSUE TITLE
Named slot inside ai-dialog not working.

### ISSUE THREAD

**Issue by Robbe64** [aurelia/dialog#277]
**I'm submitting a bug report**

* **Library Version:**
aurelia-dialog@1.0.0-beta.3.0.1
aurelia-templating@1.4.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Browser:**
Chrome 58
* **Language:**
TypeScript

**Current behavior:**
I've created a custom element for dialogs and tried to use named slots inside like this:
```
<template>
  <ai-dialog-body>
     <slot name="dialog-body">BODY_CONTENT</slot>
  </ai-dialog-body>
</template>
```
But the slot is never filled. Even the fallback content "BODY_CONTENT" is never filled.

**Workaround**
If I surround the slot with span like this, everything is working. 
`<span><slot name="dialog-body">BODY_CONTENT</slot></span>`

**Comment by StrahilKazlachev** [comment]
Not dialog related.
Also I don't see it as an issue. When using a custom element and adding a `slot`, with fallback content, as a direct child of it, you should do it to target a slot in that custom element - more [here](http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-content-projection/4).
```html
<my-element>
  <slot slot="slot-name-inside-my-element">new fallback content<slot>
</my-element>
```
Wrapping it in another element, in your case `<span>`, works since that element, with its content, gets projected into the default slot of `<ai-dialog-body>`, creating the *dialog-body* slot inside it.
@PWKad Do you see anything wrong with the explanation?
