### ISSUE TITLE
Issue changing contents of array for repeat 

### ISSUE THREAD

**Issue by schuetta92** [aurelia/dialog#44]
The following code is what I am using to filter an array, which is what is creating the "Uncaught TypeError: Cannot read property 'length' of undefined" error.

```
<div repeat.for="label of labels"></div>
```

```
set search(value){
    this.search = value;
     if (value === '' || value.length != 4){
        this.labels = this.allLabels;
      } else {
        var labels = this.allLabels.filter(x =>
                (x.item_year != null && x.item_year == value));
        this.labels = labels;
      }
  }
```

Full Error : 

```
Uncaught TypeError: Cannot read property 'length' of undefined
removeAt @ aurelia-templating.js:1041
_contentSelectorRemoveAll @ aurelia-templating.js:1400
processItems @ repeat.js:133
itemsChanged @ repeat.js:122
BindableProperty.createObserver.self
Subscriber @ aurelia-templating.js:2937
call @ aurelia-templating.js:2809
flushMicroTaskQueue @ aurelia-task-queue.js:110
(anonymous function) @ aurelia-task-queue.js:60
```

**Comment by PWKad** [comment]
Hi @schuetta92 this issue belong in aurelia-templating - also it looks like you may just not be setting `labels` to an array instance.  Please feel free to re-open this issue on templating if you feel otherwise, else check out our official gitter at http://gitter.im/aurelia/discuss and someone can surely help you get it figured out.
