### ISSUE TITLE
Dialog does not move when screen is resized.

### ISSUE THREAD

**Issue by rquast** [aurelia/dialog#55]
The dialog does not reposition itself when the screen is resized.

**Comment by rquast** [comment]
Dupe... flexbox sounds like the best idea. Didn't notice the ticket because it was closed already before the issue was resolved?

https://github.com/aurelia/dialog/issues/51

**Comment by chrismbeckett** [comment]
@rquast Sorry, closed the issue as the PR on tap will imho resolve the issue. JavaScript positioning just doesn't work on mobile browsers. I have tested my own JavaScript positioning every which way and finally said it has to be pure css or its gonna break. Orientation changes are just impossible with JavaScript positioning. From that perspective, vertical centering is hard in CSS and you have really two options: transform: translateY or flexbox. Transform works on IE9, so as long as they are using CSS to layout the dialog element in the dialog container, you could overwrite the CSS and use transform instead of flexbox pretty easily to get centering that works on IE9. For older browsers, ugh, I don't have an answer. To you point, if they used Transform rather than flexbox as the default, they would get slightly better browser support.

**Comment by PWKad** [comment]
@rquast Feel free to move your questions over to the PR.  I believe there was an IE8/9 support option using JS.

As far as supporting browsers that are older than IE9 - Microsoft isn't supporting it much longer so we don't plan to officially support anything older than IE9 either.

**Comment by PWKad** [comment]
Leaving this open until the styles are updated but planning to close then, just leaving up as a reminder to check it.

**Comment by jedd-ahyoung** [comment]
Uh...so I just ran into this myself. I see that you guys are manually setting a margin-left to position the modal.

Is there any reason that you aren't simply using `margin: auto` for the width portion? That fixes the problem easily and elegantly, and it should be supported in mobile devices. I believe there may be issues with IE9 (and possibly 10) but I think it might be a better option than Flexbox (due to support, for the time being) and Javascript (because nobody wants that nightmare).

Height position can remain the same.

Any objections? I could probably put together a really quick pull request for this tonight, unless there are unforeseen issues that I've missed.

**Comment by PWKad** [comment]
PR's welcome :)

**Comment by EisenbergEffect** [comment]
@joelcoxokc Didn't you have a bunch of improvements to the dialog plugin? I've been hesitant to change things because I've been waiting on that.

**Comment by PWKad** [comment]
@EisenbergEffect The changes he submitted as a PR originally weren't really improvements as much as they are a complete re-write of styling and classes (and also some JavaScript changes) so I think until we have that PR ready to merge if we can make incremental improvements it is probably beneficial, my $0.02.

**Comment by chrismbeckett** [comment]
FYI - Microsoft is officially dumping support for IE 8/9/10 in one fell swoop next Tuesday - http://www.independent.co.uk/life-style/gadgets-and-tech/news/microsoft-ends-support-internet-explorer-version-8-9-10-a6800881.html.

Woot - maybe now we can just solve this by doing layouts with flexbox?

**Comment by EisenbergEffect** [comment]
Unfortunately, probably not for a while. We still have customers that need to support those browser. There also may be some mobile scenarios to consider.

**Comment by EisenbergEffect** [comment]
@PWKad Ok. If we have PRs then keep them rolling in. Joel's work is designed to align the dialog plugin with Aurelia Interface so that it can work correctly across various mobile platforms, etc. We can update it when it's ready. I don't think it will change the api.

**Comment by joelcoxokc** [comment]
Yeah. You will still be able to use the Existing API. The Dialog will also by nature size itself to the screen, without JS. It also has different sizing properties that can be set.

**Comment by jedd-ahyoung** [comment]
Putting together a PR for this now. (Only had to remove two lines of code.) Should I include the dist directories or do you guys only do that on a bump? I don't quite remember.

**Comment by EisenbergEffect** [comment]
Only include the src directories please.
